---
- hosts: all
  user: "{{ sudoUser }}"
  sudo: True
  roles:
    - common

- hosts: influxdb
  user: "{{ sudoUser }}"
  sudo: True
  roles:
    - { role: ansible-influxdb, tags: [ 'ansible-influxdb'] }


- hosts: grafana
  user: "{{ sudoUser }}"
  sudo: True
  roles:
     - {role: install-grafana, tags: ['install-grafana']}

- hosts: dse
  user: "{{ sudoUser }}"
  sudo: True
  roles:
    - dse-install


- hosts: opscenter
  user: "{{ sudoUser }}"
  sudo: True
  roles:
    - opscenter


- hosts: sparkmasters
  user: "{{ sudoUser }}"
  sudo: True
  roles:
    - spark-cloudera-master

- hosts: sparkworkers
  user: "{{ sudoUser }}"
  sudo: True
  roles:
    - spark-cloudera-worker


- hosts: sparkhistory
  user: "{{ sudoUser }}"
  sudo: True
  roles:
   - spark-cloudera-history


- hosts: sparkjobserver
  user: "{{ sudoUser }}"
  sudo: True
  roles:
    - spark-jobserver