---
- name: updating machine
  shell: apt-get update

- name: adding repo
  shell: echo "deb http://debian.datastax.com/community stable main" | sudo tee -a /etc/apt/sources.list.d/datastax.community.list

- name: adding repo key
  shell: curl -L https://debian.datastax.com/debian/repo_key | sudo apt-key add -

- name: updating machine
  shell: apt-get update

- name: installing opscenter
  apt: pkg=opscenter state=installed update-cache=yes
  register: opscenterd

- name: copy opscenterd.conf with custom settings
  copy: src=opscenterd.conf dest=/etc/opscenter/opscenterd.conf


- name: starting opscenter
  service: name=opscenterd enabled=yes state=started
