- name: configure spark-env.sh
  template: src=spark-env.sh dest=/etc/spark/conf/spark-env.sh

- name: configure spark-defaults.conf
  template: src=spark-defaults.conf dest=/etc/spark/conf/spark-defaults.conf

- name: configure spark metrics.properties
  template: src=metrics.properties dest=/etc/spark/conf/metrics.properties

# Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups

- name: add spark user to root group, it's workaround for spark-history server. It doesn't see job logs submitted by root users
  user: name=spark shell=/bin/bash groups=root append=yes
