---
  - name: put cloudera.list repo
    template: src=cloudera.cdh533.repo dest=/etc/apt/sources.list.d/cloudera.cdh5.sources.list

  - name: adding cdh5 repo key
    shell: curl -L http://archive.cloudera.com/cdh5/ubuntu/trusty/amd64/cdh/archive.key | sudo apt-key add -

  - name: update the repositories
    shell: apt-get update

  - name: installing spark-core
    apt: pkg={{item}} state=installed
    with_items:
      - spark-core={{ spark.packageVersion }}
